### ISSUE TITLE
rg-autocomplete

### ISSUE THREAD

**Issue by toepoke** [RiotGear/rg#1]
You've mentioned you're working on new components for RiotGear (great name btw):

rg-ga: Google Analytics
rg-map: Google Map
rg-pagination
rg-slidedeck
rg-include

May I suggest you add an autocomplete widget too?

**Comment by gregorypratt** [comment]
Yep cool, will give it a go! Just going to rename this issue to reflect the request

**Comment by gregorypratt** [comment]
Added to v1.5
