### ISSUE TITLE
Update to the latest version of BlazeCSS

### ISSUE THREAD

**Issue by cia48621793** [RiotGear/rg#103]
The latest version of BlazeCSS introduced breaking changes, for example, they decided to add namespaces for components and animations, effectively break all the RG tags. Only 1.x.y version of BlazeCSS are compatible with RG version v3.5.0. Please update immediately.

**Comment by gregorypratt** [comment]
At the moment RiotGear works with the latest v1 release, I'm in the process of updating the HTML to adopt the changes in Blaze v2. Should be a minor update to RiotGear. In the meantime reference the latest v1 release of Blaze until RiotGear has been updated
