### ISSUE TITLE
No longer using Blaze CSS classes correctly

### ISSUE THREAD

**Issue by magwo** [RiotGear/rg#105]
It seems RG no longer works properly with Blaze CSS as they changed all the class names in 2.0.

RG only works properly with the 1.x releases. This should at least be mentioned in the Install guide.

**Comment by omt66** [comment]
I noticed the same as magwo did. It doesn't work for 2.x but 1.x releases seem to be working fine!

**Comment by magwo** [comment]
I suppose the correct path would be to update all the class names in RG. But the very minimal solution would be to instruct users to use Blaze 1.x. Not mentioning this leads to a lot of wasted time.

**Comment by LasaleFamine** [comment]
Here's a +1.

I think this needs absolutely to be mentioned within the [installation page](http://riotgear.js.org/getting-started/install/). 

Anyway, someone is working on this?

**Comment by adavie1** [comment]
Check out [RiotGear2](https://riotgear2.github.io)
