### ISSUE TITLE
Chart library update but not riotgear chart component

### ISSUE THREAD

**Issue by billygl** [RiotGear/rg#107]
I have this issue:
rg.min.js:1 Uncaught TypeError: i.Bar is not a function
 I use: 
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.6/Chart.bundle.min.js"></script>

**Comment by restlessmedia** [comment]
Do you have anymore information on your issue? From the minified source, i.Bar is a call to a method on a new Chart instance. Could you set-up a jsfiddle so we can reproduce it?

**Comment by billygl** [comment]
The issue is the i'm using the new version of http://www.chartjs.org/.
I works fine with the older one.
