### ISSUE TITLE
interested in taking over project

### ISSUE THREAD

**Issue by adavie1** [RiotGear/rg#114]
Hi,
I'm possibly interested in taking over the project. I'm in the process of fixing the Blaze 1.0 => Blaze 2.0 issues for my own use. Happy to make them available to others once I'm done.
Regards,
Anthony

**Comment by adavie1** [comment]
This is still in progress- the folders I've worked with are **dist** and the **rg.js** file only.

[https://github.com/adavie1/rg](https://github.com/adavie1/rg)

As you can see from the dist comments, I'm up to the placeholdit tag.

**Comment by adavie1** [comment]
Given there has been no reply, I've forked the repo and the website, please find the official RiotGear2 page at: [https://riotgear2.github.io/](https://riotgear2.github.io/)

**Comment by gregorypratt** [comment]
I sent you a repo invite which I've since cancelled in favour of an organisation owner invite ;)

**Comment by gregorypratt** [comment]
With that invite you should have complete control over the organisation and it's repos - really like what you've done with RG so far - I just don't have the time at the moment to commit to it.

Really looking forward to seeing where you can take it!

**Comment by adavie1** [comment]
Hi Greg! Thanks for those comments! Very happy to contribute.
