### ISSUE TITLE
rg-datepicker

### ISSUE THREAD

**Issue by Bleeky** [RiotGear/rg#25]
It would be nice to create a simple and sober date picker (year, month and day).

**Comment by gregorypratt** [comment]
Excellent shout! Date pickers are not easy to do, but let's give it a go!

**Comment by rkmax** [comment]
Please take in account i18n when built this component you can use [momentjs][1] to calculate dates and format support i18n for free

[1]: http://momentjs.com

**Comment by gregorypratt** [comment]
Will do. I was planning on using moment. It's such a comprehensive library it'd be daft not to. Might even build an rg-moment tag to output dates, as a precursor to this tag. Or extract it from this tag at a later date.

**Comment by rkmax** [comment]
@gregorypratt do you have some implemented? cos I'm planning do something this weekend :smile:

**Comment by gregorypratt** [comment]
Not started either yet! Just planned it...

Greg

**Comment by gregorypratt** [comment]
@rkmax if you do build anything could you please follow the template project I've just committed to https://github.com/RiotGear/rg-datepicker? Thanks!

**Comment by rkmax** [comment]
Sure I did that even I copy the package.json from another component to
follow the same structure

**Comment by gregorypratt** [comment]
Nice one. I'd like to start simple and only add functionality if required. Let's take an iterative approach so we know its what people want ;-)

Thanks for your contributions!

**Comment by rkmax** [comment]
@gregorypratt I did a basic [datepicker][1] but I need some directions, for example I need understand a bit more how the update works cos I used the event `update` to rebuild the calendar but riot throws an error when I rebuild the calendar

![captura de pantalla de 2015-07-18 01-29-02](https://cloud.githubusercontent.com/assets/395707/8760640/5153bdb4-2cee-11e5-85fd-e2936751df08.png)

 maybe I'm using wrong the event, I'll send you a PR

[1]: https://github.com/rkmax/rg-datepicker

**Comment by gregorypratt** [comment]
Thanks! I'll take a look at your PR over the weekend :+1:

**Comment by gregorypratt** [comment]
Going to update RiotGear with https://github.com/RiotGear/rg-datepicker and release v1.7 soon.

Thanks to @rkmax!

**Comment by rkmax** [comment]
Very nice! :+1: x :100:

**Comment by steveoliver** [comment]
This component is gone? :(

**Comment by steveoliver** [comment]
@gregorypratt Is there any way I can get access to the old rg-datepicker repo?  I should have cloned it when it was still up.

**Comment by steveoliver** [comment]
Since the standalone rg-datepicker is no longer hosted under RiotGear's GH account, I've used rkmax's [rg-datepicker](https://github.com/rkmax/rg-datepicker) instead of the new rg-date, which works better for my app.
