### ISSUE TITLE
rg-tabs: active class isn't set on header on Riot 2.2.1

### ISSUE THREAD

**Issue by miloszw** [RiotGear/rg#26]
The `active` class is correctly set upon mount, but later doesn't get updated when switching tabs. Everything else seems to work as expected.

http://codepen.io/anon/pen/Wvzmpw

Also, if you change the riot url to just 2.2 (instead of 2.2.1) which should pull down the latest version, nothing gets rendered at all. This might be due to the fact the latest 2.2.2 release is still in beta though, so it might not be a rg issue.

**Comment by gregorypratt** [comment]
Hmmm, seems to work with 2.1. Will investigate and fix it

**Comment by gregorypratt** [comment]
Other components seem to be unaffected - I've raised the issue with the Riot team https://github.com/riot/riot/issues/939 who will no doubt work on a fix. In the meantime using v2.1 is the work around...

**Comment by miloszw** [comment]
Thanks for the update! Curious as to what broke it.. :thought_balloon:

**Comment by gregorypratt** [comment]
Me too! :-)

**Comment by gregorypratt** [comment]
Will be fixed as part of next Riot release: https://github.com/riot/riot/issues/939
