### ISSUE TITLE
rg-tag

### ISSUE THREAD

**Issue by Bleeky** [RiotGear/rg#33]
It could be a good idea to add a tag selector ! (See this example : http://mbenford.github.io/ngTagsInput/demos).

**Comment by gregorypratt** [comment]
Yeah nice one, I'll setup a repo for it

**Comment by gregorypratt** [comment]
@Bleeky https://github.com/RiotGear/rg-tags any good?

**Comment by Bleeky** [comment]
Sounds good ! Maybe just add the possibility to add a closing cross (better UX for some cases). ;)

**Comment by gregorypratt** [comment]
Will do :+1:

**Comment by gregorypratt** [comment]
Added a close cross - https://riotgear.github.io/components/tags/
