### ISSUE TITLE
[rg-context-menu] open menu upward if aint enough space below the mouse pointer

### ISSUE THREAD

**Issue by nippur72** [RiotGear/rg#34]
When the mouse pointer is close to the bottom border of the page, opening a `<rg-context-menu>` causes it to go off screen. In such cases, the menu should open upward.

**Comment by gregorypratt** [comment]
Totally agree! Was going to address this in a later iteration..

**Comment by gregorypratt** [comment]
https://riotgear.github.io/components/context-menu/ - menu should now behave correctly
