### ISSUE TITLE
include the '.tag' file in the "Download" section

### ISSUE THREAD

**Issue by javierguerragiraldez** [RiotGear/rg#35]
Currently, the "Download" section of each component makes it easy to pull compiled '.js' and '.min.js' files.  To get the '.tag' file for in-browser compilation i have to go to the GitHub repository.

Not a big deal, but simply listing it too would make the rg collection much nicer to just try out.

**Comment by gregorypratt** [comment]
Yep good shout. I'll add the links to the site...

**Comment by gregorypratt** [comment]
Done. I've added links to the `src` directories rather than the files themselves since there might be more than one tag file and its easier to maintain this way ;-)
