### ISSUE TITLE
rg-timepicker

### ISSUE THREAD

**Issue by Bleeky** [RiotGear/rg#36]
Let's add a time picker (with hours, minutes and optional seconds). :smile:

**Comment by gregorypratt** [comment]
You got it!

**Comment by Bleeky** [comment]
It's a little bit different from a date-picker !

**Comment by gregorypratt** [comment]
Yeah no worries. Just on holiday at the moment. But I'll tackle this when I get back ;-)

**Comment by Bleeky** [comment]
Enjoy ! :smiley:

**Comment by gregorypratt** [comment]
What do you reckon?
https://riotgear.js.org/components/timepicker/
Doesn't handle seconds. Didn't think it needed them for the MVP...
