### ISSUE TITLE
rg-autocomplete should extends rg-select

### ISSUE THREAD

**Issue by devhero** [RiotGear/rg#41]
Hi,
first of all: *great job!*

I think that to adhere to a modular style the component rg-autocomplete should extends the rg-select, or at least they should extends a more basic component.
Another good technic could be tu use composition for common functions such sharing a mixin module.
I didn't inspect all components but this should be the way for all modules.

**Comment by gregorypratt** [comment]
Yes you are correct. I started following the pattern when I did [rg-timepicker](https://github.com/RiotGear/rg-timepicker/blob/master/src/rg-timepicker.tag#L3)...

And have been thinking about mixins recently for things like overlays etc. bits that people could use outside of components but that the components could use themselves

**Comment by gregorypratt** [comment]
As part of v2 (not released yet) 
https://github.com/RiotGear/rg/blob/master/components/select/rg-select.tag#L4

rg-autocomplete is removed and is simply an option on rg-select
