### ISSUE TITLE
Form example

### ISSUE THREAD

**Issue by goldalworming** [RiotGear/rg#46]
Hi, thank you for your library, but I have searched everywhere and I don't get any sample to combine riot or riotgear to ajax post

can you give some example to use rg-select, rg-datepicker with crud form and post itu to backend.
I think riot.js really lack of ajax example.

**Comment by gregorypratt** [comment]
Yeah once the v2.0.0-rc1 has been released I'll knock up an example

**Comment by goldalworming** [comment]
hi @gregorypratt , where could I find form example in website?

**Comment by gregorypratt** [comment]
Sorry forgot about this. Here's an example plunk. http://plnkr.co/edit/iB4jdLKHjVF5j9O8mZvA?p=preview
