### ISSUE TITLE
Material Theme

### ISSUE THREAD

**Issue by leonuh** [RiotGear/rg#47]
Hi there,

I would like to know about the structure concerning the material theme. How do you want to extend the current components, or do you want to separate them from the existed ones? Besides what are your plans for the css part? Reuse an existed project (eg.: http://materializecss.com/) or something else? There are tags that are useful in general but there are some that maybe not consistent with the material concept. There are cases (eg.: datepicker) where the current behavior(class) itself is not reusable in a material based datepicker tag.
Could you please provide a skeleton and give more information about the roadmap?

Thank you!

**Comment by gregorypratt** [comment]
I plan on writing (only) CSS that makes it look and act like material. That's about all the info I have right now! I'm still in the middle of the refactor for v2. Once that's done I'm going to get on with themes.

**Comment by gregorypratt** [comment]
This isn't happening anytime soon. Unless someone wants to produce the theme themselves and make a PR then I'm for it! Otherwise the Roadmap draws too much time https://github.com/RiotGear/rg/issues/66 to address producing themes
