### ISSUE TITLE
ES6 classes on production?

### ISSUE THREAD

**Issue by believer-ufa** [RiotGear/rg#48]
As i see, you use a ES6 classes in some RG components.

But how use this code on production? Just some new versions of browsers have this implementation.

**Comment by gregorypratt** [comment]
Babel.io 😉

Eg. https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=class%20Cat%20%7B%0A%20%20%0A%7D

**Comment by believer-ufa** [comment]
Many thanks) i'll try it)

**Comment by believer-ufa** [comment]
Its works) thanks again.
