### ISSUE TITLE
rg-tabs tab index initialization

### ISSUE THREAD

**Issue by mheilman** [RiotGear/rg#49]
In the tabs component, the tab indices are currently initialized in the `mount` event handler.

It seems like it would be better to initialize the indices right away (i.e., outside of an event handler), so that tabs have indices immediately.  Would that break anything?  Doing so seems to work fine for me, but perhaps there's some reason the index initialization happens in the `mount` callback.

I ran into this trying to use riot's router to switch to a particular tab based on `location.hash` when the page is loaded.

I can make a PR if that'd be helpful.  Would that go here or the `rg-tabs` repo?

**Comment by gregorypratt** [comment]
You may load the page but never mount the tag depending on the situation. Which means the code is only executed when required. Its a pattern that the tags are following to ensure the superfluous code is executed regardless of situation....does that answer your question?

At the moment the v2.0.0-rc1 refactor is well underway and rg-tabs hasn't been touched yet so if you want to submit a PR I'd wait until after rc1 is released ;-)

**Comment by gregorypratt** [comment]
Closing this. Pls reopen if it becomes relevant again
