### ISSUE TITLE
require riotgear cannot find riot

### ISSUE THREAD

**Issue by skandasoft** [RiotGear/rg#52]
I did require riotgear. it gives runtime error of riot not found. I have done npm riot as well

**Comment by gregorypratt** [comment]
I'm going to need more info to help.
Server or client?
What does your code look like?

**Comment by gregorypratt** [comment]
18 days old with no response. Closing.

**Comment by MartinMuzatko** [comment]
Same problem here. this happens if you just require riotgear without a riot object in place. 

requiring riotgear doesn't give back anything other than an empty object though
