### ISSUE TITLE
waiting material

### ISSUE THREAD

**Issue by ohohco** [RiotGear/rg#53]

**Comment by gregorypratt** [comment]
Duplicate of this one? https://github.com/RiotGear/rg/issues/47

v2.0.0-rc1 refactoring is almost complete. Once done the material theme is next. Its going slower than expected as I've broken my collarbone!

https://twitter.com/grumpywizards/status/653611717985988609

**Comment by sylvainpolletvillard** [comment]
Hope you get well soon :) Great job you've done with RiotGear in so little time.

**Comment by ohohco** [comment]
Hope you get well soon :)

**Comment by gregorypratt** [comment]
Closing in favour of this one https://github.com/RiotGear/rg/issues/47
