### ISSUE TITLE
Update website docs

### ISSUE THREAD

**Issue by hauran** [RiotGear/rg#54]
http://riotgear.js.org/components/modal/ says attribute is visible
but should be **isvisible**

**Comment by gregorypratt** [comment]
Updated this issue's title to be wider. Currently in the middle of updating the website so this should be closed tomorrow or the day after

**Comment by hauran** [comment]
Thanks.
is toggle docs also wrong? but cant seem to get it to work even looking at source.
what would be helpful for contributing is seeing the .tag file

**Comment by gregorypratt** [comment]
The docs will be up to date sometime today...

Take a look at the demo app.tag in the meantime. Might help while the site is being changed...

**Comment by hauran** [comment]
that helps. thanks.

**Comment by gregorypratt** [comment]
riotgear.github.io
