### ISSUE TITLE
custom tag in rg-modal is not evaluated

### ISSUE THREAD

**Issue by whatda** [RiotGear/rg#63]
Hi,

thanks for your great library.

While playing around I found a possible bug: If the content of a button is set to an html string which contains a riot tag, the tag is not evaluated correctly. I get the custom tag inside the button, but its html is empty.

Any help is appreciated, thanks.

**Comment by gregorypratt** [comment]
Right that's a scenario I never thought about! I think I could wrap a riot compile in the rg-raw tag to fix this. It would also fix it in other content: "" instances...watch this space

**Comment by gregorypratt** [comment]
Actually I think we'll need to wait until v2.4.0 of Riot is released to make use of the additional compiler APIs

**Comment by gregorypratt** [comment]
Does this work now?

Example:
https://plnkr.co/edit/35HE8BJtzfEdp5b42vtX?p=preview
