### ISSUE TITLE
Loading tag -- absolute -> fixed?

### ISSUE THREAD

**Issue by ckcollab** [RiotGear/rg#65]
Hey there, first of all thanks for this library! 

I'm using the loading tag and I was wondering if it could be changed from `position: absolute` to `position: fixed` so it takes up the whole screen even if there's scroll space beneath the screen when user scrolls?

I also may have been using it wrong (relative to wrong container?) so not sure.

**Comment by gregorypratt** [comment]
Thanks for the feedback :+1:

It was either a choice of relating the overlays (loading, modal etc) to their parent elements or making them full page. It boiled down to personal opinion and the component nature that I chose the parent element to be the default (blocking the full screen is sometimes necessary but it isn't the best user experience).

However to make the component full screen simply override the CSS selector and apply your own specific rules.

```css
  rg-loading .overlay,
  rg-loading .content {
    position: fixed;
  }
```

Hope this helps!

**Comment by ckcollab** [comment]
Ah, right, thanks :)
