### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by seemsindie** [RiotGear/rg#73]
Hello, i am pretty new to riot. And i have a starter project https://github.com/wbkd/riotjs-startkit

And i installed riotgear with npm, now when i try some examples from website i get white page without errors.  I also tried importing riotgear in index.js, but still the same result.

Any ideas why?

**Comment by gregorypratt** [comment]
Will clone your repo and give it a go...

**Comment by gregorypratt** [comment]
If this is causing you problems with the latest version re-open this issue
