### ISSUE TITLE
global variables, necessary usage of constructor function

### ISSUE THREAD

**Issue by Vantraninthena** [RiotGear/rg#74]
I'm using the version from
```html
<script src="https://cdn.jsdelivr.net/riotgear/2.1.3/rg.min.js"></script>
```

Why do I need to use a constructor function to use the components ?
E.g., why do i need to write

```javascript
   this.tabs = new RgTabs({
      tabs: [{
        heading: 'Tab <em>one</em>',
        content: 'This is tab one'
      }, {
        heading: 'Tab two',
        content: 'This is tab two',
        active: true
      }, {
        heading: 'Disabled tab',
        content: 'This is disabled tab',
        disabled: true
      }, {
        heading: 'Tab three',
        content: 'This is tab three content',
        include: new RgInclude({
          url: 'tab.html',
          unsafe: true
        })
      }]
    })
```
instead of

```javascript
this. tabs =  [{
      heading: 'Tab <em>one</em>',
      content: 'This is tab one'
    }, {
      heading: 'Tab two',
      content: 'This is tab two',
      active: true
    }, {
      heading: 'Disabled tab',
      content: 'This is disabled tab',
      disabled: true
    }, {
      heading: 'Tab three',
      content: 'This is tab three content',
      include: new RgInclude({
        url: 'tab.html',
        unsafe: true
      })
    }]
```
It pollutes the global space and (at least for now) i don't see any added value offered by the constructor.

Are there any plans to change it, or am I completely missing the point of having those globals instead of just registering the component with riot ?

Best regards

**Comment by gregorypratt** [comment]
Each RiotGear component has custom methods and is an observable. Each one also has an update method you can call that only updates that specific tag.

If you can suggest a refactor that removes the globals but retains the functionality then I'd be happy to review it!

**Comment by gregorypratt** [comment]
Also you don't need to use the constructor if you don't want. The tag will accept opts and use the constructor behind the scenes...if you come up with a different approach I could incorporate it in to v3 currently in development

**Comment by Vantraninthena** [comment]
Thanks for the answer.
Why are you not using your rg namespace for delivering the constructors ? Doesn't solve the problem, but at least it bundles all components in one place ( e.g. rg.Select, rg.Tab). I will think about a better solution after my finals.

I've seen the

```javascript
_this.RgTabs = opts.tabs || new RgTabs(opts);
```

line, but this only applies if i mount it through coding right ?
Or is there a possibiliy to pass the opts object directly through a tag ?

```html
<rg-tabs tabs = { tabs } ></rg-tabs>
```
With this pattern opts will always have a .tab property declared if i understand it correctly.
Or maybe you could provide me with an example if there is a easy way to do it, and i'm just not seeing it.

Best regards

**Comment by gregorypratt** [comment]
Your example of `tabs={ tabs }` works when passing in an RgTabs instance.

Alternatively you can specify each property of the class as an attribute that gets added to opts (and fed into the constructor in the tag). Either way the tag uses an RgTabs instance whether you build one or it does it for you. Does that make any sense?! :-)

I'm transpiling the code through Babel so the classes become constructors. Also I'm using inheritance for some tags that are related like select. I'll look into utilising rg to clean up the global space :+1:

**Comment by Vantraninthena** [comment]
So is it possible to get my example working without passing a RgTabs instance by just passing an array that gets fed into the constructor ?

```html
<heisig-shell>
  <rg-tabs tabs={tabs} ></rg-tabs>
  <script>
   this.tabs =[{
        heading : 'Heisig'
        ,content : '#Heisig'
      },{
        heading : 'Anki'
        ,content : '#Anki'
      },{
        heading : 'FAQ'
        ,content : '#FAQ'
      },{
        heading : 'Tobira'
        ,content : '#Tobira'
      },{
        heading : 'Jisho'
        ,content : '#Jisho'
      },{
        heading : 'Maintenance'
        ,content   : '#Maintenance'
      }
    ]
  </script>
</heisig-shell>
```

By passing it like this, the resulting constructor object for your component will look like this : 
```javascript
opts = {
   tabs : [..]
}
```
And your mount function
```javascript
		this.on('mount', () => {
			this.RgTabs = opts.tabs || new RgTabs(opts)
			this.RgTabs.on('update', () => {
				this.update()
			})
			this.update()
		})
```
will get an opts object with opts.tab defined and will therefore not instantiate a new RgTabs instance. Which results in the tabs not working.
By calling it like this
```javascript
riot.mount("rg-tabs", [{heading:....,content:..}])
```
the resulting opts object looks like this
```javascript
opts = [{heading:....,content:..}]
```
opts would not have the property tabs and the condition would result into new RgTabs(opts).

The behavior i want could be achieved like this
```javascript
const tabs  = opt.tabs ? opt.tabs : opt;
this.RgTabs = tabs instanceof RgTabs ? tabs : new RgTabs(tabs);
```
Do you know what i mean ?

**Comment by gregorypratt** [comment]
Does
```
   this.tabs = { tabs: [{
        heading : 'Heisig'
        ,content : '#Heisig'
      },{
        heading : 'Anki'
        ,content : '#Anki'
      },{
        heading : 'FAQ'
        ,content : '#FAQ'
      },{
        heading : 'Tobira'
        ,content : '#Tobira'
      },{
        heading : 'Jisho'
        ,content : '#Jisho'
      },{
        heading : 'Maintenance'
        ,content   : '#Maintenance'
      }
    ]}
```
Work?

**Comment by gregorypratt** [comment]
Yeah your code would work I reckon...I'll give it a go in v3 and see how it goes.

In the meantime v2.x won't be getting an update (it would just be too much!)

**Comment by Vantraninthena** [comment]
Sadly no, because the opt still has the property tabs and doesn't pass the condition in
```javascript
this.RgTabs = opts.tabs || new RgTabs(opts)
```
I found an older issue for riotjs where someone asked whether its possible to declare the opt object in a tag the same way you can do it with mounting. Answer was that it's not possible atm, and probably also won't be supported.

I will fork this repo and experiment a bit, if I have something that i think could add some value i will send a pull request.
Thanks for your patience and answers !

**Comment by crearc** [comment]
I second this. I saw you mentioned you want to be able to still call methods like update. You can name the tag, access the tag with `this.tags.myTag` and call methods from there, right?
