### ISSUE TITLE
Playground not working

### ISSUE THREAD

**Issue by kewp** [RiotGear/rg#79]
Trying to get the demo in Playground to work on Firefox but it's not working.

At first I saw nothing (between the title and the code block).

Then I got the text ( Change the code in the editor below and see the output update instantly.
« Open side menu » ).

However, clicking on 'Open side menu' does nothing.

Am getting a TypeError on the console ... (See attached image). Looks like the library isn't loading at all.

Firefox 44.0.
Ubuntu 14.04.1, x86_64

I've tried the same thing with Chrome (48.0.2564.103 (64-bit)).
Same thing.

**Comment by gregorypratt** [comment]
Yeah this has been borked for a while, I've literally just removed it from the code as part of the v3 documentation update.

v3 should be live by the end of the week.
