### ISSUE TITLE
riot is not defined

### ISSUE THREAD

**Issue by sproktec** [RiotGear/rg#80]
I'm trying to get riotgear working with System.js but have been going round the houses trying to work it out. I've tried shimming riot into riotgear in the config

```
  meta: {
    "riotgear": {
      "deps": [
        "riot"
      ]
    },
  }
```
then importing riot and riotgear in my module
```
import riot from 'riot';
import RiotGear from 'riotgear';
```
but before anything happens I'm getting Uncaught ReferenceError: riot is not defined. I've been through installing with npm and just using it in a vendor folder but no matter what configuration I use I get the same thing. I think it's trying to initialise before riot is loaded. I've tried a few edits to riotgear but I can't work it out.

**Comment by gregorypratt** [comment]
Is this still a problem with v3.2.0?

Is this a problem with Riot or RiotGear?

**Comment by sproktec** [comment]
It is still a problem but I'm thinking it's more a problem with System.js than RiotGear & Riot. They don't play well together at the moment but I think it's more to do with RiotGear needing to shim Riot in and System.js not dealing with this. If I get anywhere I'll let you know

**Comment by gregorypratt** [comment]
Re-open if you want

**Comment by cigzigwon** [comment]
Is anybody NOT using webpack yet? I am. @sproktec is there any way to get it working with "import"

**Comment by cigzigwon** [comment]
add this plugin and the problem is solved

```
const providerPlug = new webpack.ProvidePlugin({
  riot: 'riot'
})
```
