### ISSUE TITLE
Autocomplete for complex objects

### ISSUE THREAD

**Issue by lupeportias** [RiotGear/rg#94]
Hello, I am looking for an autocomplete that searches an array with objects with 2 items inside each. 
The autocomplete should match characters within each item in each object and print a response of each object that matches showing the 2 items inside those objects. 
Can anyone recomend a library?

**Comment by gregorypratt** [comment]
Does [Select2](https://select2.github.io/) cover your needs? I think it uses JQuery.

**Comment by gregorypratt** [comment]
As part of v3.4 I've added a filter property to the select component. It doesn't search all properties yet but there's scope to do so.

**Comment by lupeportias** [comment]
Greg, we ended up using this: [http://richardbondi.net/riot/]
thanks!
