### ISSUE TITLE
pagination highlights focussed page

### ISSUE THREAD

**Issue by continuata** [RiotGear/rg#95]
this can be recreated on the RG demo page

If you click on a page number, it switches to the new selection, but leaves the button that was pressed highlighted (which now contains a different page number)

e.g. 
![screen shot 2016-03-21 at 14 20 16](https://cloud.githubusercontent.com/assets/1593397/13921546/457172e4-ef70-11e5-9e68-b6a2977cca61.png)
clicking on `7` gives:
![screen shot 2016-03-21 at 14 20 22](https://cloud.githubusercontent.com/assets/1593397/13921549/48800f5e-ef70-11e5-8ffb-b7a457044e0a.png)

`8` should not be highlighted.
I'm guessing it's a focus styling.

**Comment by gregorypratt** [comment]
Not actually a problem with blaze, turned out the buttons needed to be blurred manually
